#!/usr/bin/env python
"""
Build BMC-style machine-readable additional files.

The manuscript refers to machine-readable supplementary tables. This script
collects the traceable CSV/XLSX outputs already generated by the numbered
pipeline scripts and packages them as BMC-friendly "Additional file" workbooks.
"""

from __future__ import annotations

import json
import shutil
import zipfile
from pathlib import Path

import pandas as pd


PROJECT_DIR = Path(__file__).resolve().parents[1]
OUT_DIR = PROJECT_DIR / "manuscript" / "additional_files"
OUT_DIR.mkdir(parents=True, exist_ok=True)


def rel(path: Path) -> str:
    return str(path.relative_to(PROJECT_DIR)).replace("\\", "/")


def safe_sheet_name(name: str, used: set[str]) -> str:
    invalid = set('[]:*?/\\')
    cleaned = "".join(ch if ch not in invalid else "_" for ch in name)
    cleaned = cleaned[:31] or "Sheet"
    base = cleaned
    i = 1
    while cleaned in used:
        suffix = f"_{i}"
        cleaned = (base[: 31 - len(suffix)] + suffix)[:31]
        i += 1
    used.add(cleaned)
    return cleaned


def read_table(path: Path) -> pd.DataFrame:
    if path.suffix.lower() == ".xlsx":
        frames = pd.read_excel(path, sheet_name=None)
        rows = []
        for sheet, df in frames.items():
            tmp = df.copy()
            tmp.insert(0, "source_sheet", sheet)
            rows.append(tmp)
        return pd.concat(rows, ignore_index=True) if rows else pd.DataFrame()
    return pd.read_csv(path)


def write_workbook(filename: str, title: str, description: str, sources: list[tuple[str, Path]]) -> dict:
    out = OUT_DIR / filename
    used: set[str] = set()
    with pd.ExcelWriter(out, engine="openpyxl") as writer:
        meta = pd.DataFrame(
            [
                {"field": "title", "value": title},
                {"field": "description", "value": description},
                {"field": "generated_from_project", "value": str(PROJECT_DIR)},
            ]
        )
        meta.to_excel(writer, sheet_name="README", index=False)
        source_rows = []
        for label, path in sources:
            if not path.exists():
                source_rows.append({"label": label, "source_path": rel(path), "status": "missing", "rows": 0, "columns": 0})
                continue
            df = read_table(path)
            sheet = safe_sheet_name(label, used)
            if df.shape[0] > 1_048_000:
                df = df.head(1_048_000).copy()
                df.insert(0, "xlsx_truncated_note", "truncated_to_excel_row_limit")
            df.to_excel(writer, sheet_name=sheet, index=False)
            source_rows.append(
                {
                    "label": label,
                    "sheet": sheet,
                    "source_path": rel(path),
                    "status": "included",
                    "rows": int(df.shape[0]),
                    "columns": int(df.shape[1]),
                }
            )
        pd.DataFrame(source_rows).to_excel(writer, sheet_name="source_manifest", index=False)
    return {"file": out.name, "title": title, "description": description, "path": rel(out), "bytes": out.stat().st_size}


def write_code_archive() -> dict:
    out = OUT_DIR / "Additional_file_11_code_archive.zip"
    include_dirs = [PROJECT_DIR / "scripts", PROJECT_DIR / "manuscript" / "reproducibility_package"]
    excluded_script_files = {"18_build_manuscript_draft.py"}
    include_files = [
        PROJECT_DIR / "README.md",
        PROJECT_DIR / "manuscript" / "repository_deposit_README.md",
    ]
    with zipfile.ZipFile(out, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for folder in include_dirs:
            for path in sorted(folder.rglob("*")):
                if path.is_file() and "__pycache__" not in path.parts:
                    if path.parent.name == "scripts" and path.name in excluded_script_files:
                        continue
                    zf.write(path, rel(path))
        for path in include_files:
            if path.exists():
                zf.write(path, rel(path))
    return {
        "file": out.name,
        "title": "Analysis code archive",
        "description": "Numbered analysis scripts, README file, software environment notes, and reproducibility instructions.",
        "path": rel(out),
        "bytes": out.stat().st_size,
    }


def write_binary_file(filename: str, title: str, description: str, source: Path) -> dict:
    out = OUT_DIR / filename
    if source.exists():
        shutil.copyfile(source, out)
    else:
        out.write_text(f"Missing expected source file: {rel(source)}\n", encoding="utf-8")
    return {"file": out.name, "title": title, "description": description, "path": rel(out), "bytes": out.stat().st_size}


def main() -> None:
    files = []
    files.append(
        write_workbook(
            "Additional_file_1_dataset_metadata_and_qc.xlsx",
            "Dataset metadata and QC",
            "Bulk, miRNA, and single-cell annotation and expression-matrix QC tables.",
            [
                ("bulk_mirna_annotation", PROJECT_DIR / "metadata/all_bulk_mirna_annotation.csv"),
                ("bulk_mirna_annotation_qc", PROJECT_DIR / "metadata/all_bulk_mirna_annotation_qc.csv"),
                ("expression_matrix_qc", PROJECT_DIR / "metadata/expression_matrix_qc.csv"),
                ("dataset_matrix_qc", PROJECT_DIR / "metadata/expression_matrix_qc.csv"),
                ("matrix_processing_decisions", PROJECT_DIR / "metadata/matrix_processing_decisions.csv"),
                ("all_sample_label_audit", PROJECT_DIR / "metadata/all_bulk_mirna_sample_label_audit.csv"),
                ("sample_label_audit_all_datasets", PROJECT_DIR / "metadata/all_bulk_mirna_sample_label_audit.csv"),
                ("all_sample_label_audit_qc", PROJECT_DIR / "metadata/all_bulk_mirna_sample_label_audit_qc.csv"),
                ("gse110147_sample_label_audit", PROJECT_DIR / "metadata/gse110147_sample_label_audit.csv"),
                ("single_cell_sample_annotation", PROJECT_DIR / "metadata/single_cell/single_cell_sample_annotation.csv"),
                ("single_cell_annotation_validation", PROJECT_DIR / "metadata/single_cell/single_cell_annotation_validation.csv"),
            ],
        )
    )
    files.append(
        write_workbook(
            "Additional_file_2_differential_expression_results.xlsx",
            "Differential expression results",
            "Annotated differential-expression summaries and QC outputs.",
            [
                ("all_significant_annotated", PROJECT_DIR / "results/differential_expression_annotated/all_significant_annotated_gene_or_mirna_level_fdr0.05_logfc1.csv"),
                ("all_significant_raw", PROJECT_DIR / "results/differential_expression/all_significant_de_features_fdr0.05_logfc1.csv"),
                ("de_qc", PROJECT_DIR / "results/differential_expression/differential_expression_qc.csv"),
                ("feature_annotation_map", PROJECT_DIR / "results/feature_annotation/feature_annotation_map.csv"),
                ("feature_annotation_qc", PROJECT_DIR / "results/feature_annotation/feature_annotation_qc.csv"),
            ],
        )
    )
    files.append(
        write_workbook(
            "Additional_file_3_robust_candidates.xlsx",
            "Robust mRNA and miRNA candidates",
            "Discovery-validation robust candidate tables, direction matrices, and dataset-specific validation-support rules.",
            [
                ("robust_mrna_strict", PROJECT_DIR / "results/robust_candidates/robust_mrna_candidates_strict.csv"),
                ("robust_mirna_strict", PROJECT_DIR / "results/robust_candidates/robust_mirna_candidates_strict.csv"),
                ("mrna_direction_matrix", PROJECT_DIR / "results/robust_candidates/mrna_direction_matrix.csv"),
                ("mirna_direction_matrix", PROJECT_DIR / "results/robust_candidates/mirna_direction_matrix.csv"),
                ("validation_support_rule_by_dataset", PROJECT_DIR / "results/robust_candidates/validation_support_rule_by_dataset.csv"),
                ("validation_support_rule_qc", PROJECT_DIR / "results/robust_candidates/validation_support_rule_qc.csv"),
                ("robust_candidate_qc", PROJECT_DIR / "results/robust_candidates/robust_candidate_qc.csv"),
            ],
        )
    )
    files.append(
        write_workbook(
            "Additional_file_4_mirna_mrna_axes.xlsx",
            "miRNA-mRNA candidate axes",
            "miRTarBase-derived opposite-direction candidate axes, evidence grading, exact-axis support table, target-set stress tests, hsa-miR-375 target release-like score, relaxed exploratory axes, and paired-correlation audit.",
            [
                ("axes_evidence_graded", PROJECT_DIR / "results/submission_enhancements/mirna_mrna_axes_evidence_graded.csv"),
                ("mirna_evidence_grading", PROJECT_DIR / "results/submission_enhancements/mirna_mrna_axes_evidence_graded.csv"),
                ("exact_axis_support", PROJECT_DIR / "results/submission_enhancements/mirna_exact_axis_support_table.csv"),
                ("exact_axis_support_qc", PROJECT_DIR / "results/submission_enhancements/mirna_exact_axis_support_qc.csv"),
                ("target_set_enrichment", PROJECT_DIR / "results/mirna_program_support/robust_mirna_target_set_enrichment.csv"),
                ("mir375_repression_score", PROJECT_DIR / "results/mirna_program_support/hsa_mir_375_target_repression_release_score.csv"),
                ("relaxed_axis_sensitivity", PROJECT_DIR / "results/mirna_program_support/relaxed_mirna_axis_sensitivity_set.csv"),
                ("paired_correlation_audit", PROJECT_DIR / "results/mirna_program_support/paired_mirna_mrna_correlation_audit.csv"),
                ("mirna_program_qc", PROJECT_DIR / "results/mirna_program_support/mirna_program_support_qc.csv"),
                ("figure_s14_manifest", PROJECT_DIR / "results/mirna_program_support/figure_s14_manifest.csv"),
                ("axes_mirtarbase", PROJECT_DIR / "results/mirna_mrna_axes/robust_mirna_mrna_negative_axes_mirtarbase.csv"),
                ("top100_axes", PROJECT_DIR / "results/mirna_mrna_axes/top100_robust_mirna_mrna_axes.csv"),
                ("mirna_axis_summary", PROJECT_DIR / "results/mirna_mrna_axes/mirna_axis_summary.csv"),
                ("target_gene_axis_summary", PROJECT_DIR / "results/mirna_mrna_axes/target_gene_axis_summary.csv"),
                ("axis_qc", PROJECT_DIR / "results/mirna_mrna_axes/mirna_mrna_axis_qc.csv"),
            ],
        )
    )
    files.append(
        write_workbook(
            "Additional_file_5_enrichment_results.xlsx",
            "GO/KEGG/Reactome enrichment results",
            "Enrichment results, gene-set inputs, and enrichment QC tables.",
            [
                ("all_enrichment_results", PROJECT_DIR / "results/enrichment/all_enrichment_results.csv"),
                ("all_enrichment_significant", PROJECT_DIR / "results/enrichment/all_enrichment_significant_fdr0.05.csv"),
                ("robust_mrna_strict_enrichment", PROJECT_DIR / "results/enrichment/robust_mrna_strict_enrichment_significant_fdr0.05.csv"),
                ("gene_sets_used", PROJECT_DIR / "results/enrichment/gene_sets_used.csv"),
                ("gene_id_mapping", PROJECT_DIR / "results/enrichment/gene_id_mapping.csv"),
                ("enrichment_triple_qc", PROJECT_DIR / "results/enrichment/enrichment_triple_qc.csv"),
            ],
        )
    )
    files.append(
        write_workbook(
            "Additional_file_6_string_ppi_results.xlsx",
            "STRING PPI and hub results",
            "STRING mapping, network nodes, edges, hub metrics, and QC tables.",
            [
                ("ppi_hubs_medium", PROJECT_DIR / "results/ppi_network/string_ppi_hub_genes_robust_mrna_strict_medium_confidence.csv"),
                ("ppi_nodes_medium", PROJECT_DIR / "results/ppi_network/string_ppi_nodes_robust_mrna_strict_medium_confidence.csv"),
                ("ppi_edges_medium", PROJECT_DIR / "results/ppi_network/string_ppi_edges_robust_mrna_strict_medium_confidence.csv"),
                ("ppi_triple_qc", PROJECT_DIR / "results/ppi_network/string_ppi_triple_qc.csv"),
            ],
        )
    )
    files.append(
        write_workbook(
            "Additional_file_7_machine_learning_results.xlsx",
            "Machine-learning performance, feature stability, and perturbation triage",
            "Model performance, feature-selection stability, predictions, hyperparameter grids, final Elastic Net specification, candidate-prioritization outputs, perturbation-triage validation-planning score, and score weight-sensitivity analysis.",
            [
                ("external_validation_summary", PROJECT_DIR / "results/models/ml_outputs_discovery_only_mrna/ml_model_performance_external_validation_summary.csv"),
                ("external_validation_by_cohort", PROJECT_DIR / "results/models/ml_outputs_discovery_only_mrna/ml_model_performance_external_validation.csv"),
                ("internal_cv_summary", PROJECT_DIR / "results/models/ml_outputs_discovery_only_mrna/ml_model_performance_internal_cv_summary.csv"),
                ("final_panel", PROJECT_DIR / "results/models/ml_outputs_discovery_only_mrna/ml_final_biomarker_panel.csv"),
                ("feature_stability", PROJECT_DIR / "results/models/ml_outputs_discovery_only_mrna/ml_feature_selection_stability.csv"),
                ("external_predictions", PROJECT_DIR / "results/models/ml_outputs_discovery_only_mrna/ml_external_validation_predictions.csv"),
                ("external_bootstrap_ci", PROJECT_DIR / "results/models/ml_outputs_discovery_only_mrna/ml_external_validation_bootstrap_ci.csv"),
                ("metric_definitions", PROJECT_DIR / "results/models/ml_outputs_discovery_only_mrna/ml_metric_definitions_and_interpretation_notes.csv"),
                ("label_permutation_control", PROJECT_DIR / "results/models/ml_outputs_discovery_only_mrna/ml_permutation_label_control.csv"),
                ("ml_triple_qc", PROJECT_DIR / "results/models/ml_outputs_discovery_only_mrna/ml_triple_qc.csv"),
                ("hyperparameter_grid_summary", PROJECT_DIR / "results/models/ml_outputs_discovery_only_mrna/ml_hyperparameter_grid_summary.csv"),
                ("final_elastic_net_spec", PROJECT_DIR / "results/models/ml_outputs_discovery_only_mrna/ml_final_elastic_net_specification.csv"),
                ("ml_reproducibility_notes", PROJECT_DIR / "results/models/ml_outputs_discovery_only_mrna/ml_reproducibility_notes.csv"),
                ("oligo_actionability_index", PROJECT_DIR / "results/oligonucleotide_actionability/oligonucleotide_actionability_index.csv"),
                ("oligo_actionability_qc", PROJECT_DIR / "results/oligonucleotide_actionability/oligonucleotide_actionability_qc.csv"),
                ("actionability_weight_scores", PROJECT_DIR / "results/oligonucleotide_actionability/actionability_weight_sensitivity_all_scores.csv"),
                ("actionability_weight_ranks", PROJECT_DIR / "results/oligonucleotide_actionability/actionability_weight_sensitivity_rank_summary.csv"),
                ("actionability_weight_scenarios", PROJECT_DIR / "results/oligonucleotide_actionability/actionability_weight_sensitivity_scenario_weights.csv"),
                ("actionability_weight_qc", PROJECT_DIR / "results/oligonucleotide_actionability/actionability_weight_sensitivity_qc.csv"),
            ],
        )
    )
    files.append(
        write_workbook(
            "Additional_file_8_machine_learning_sensitivity.xlsx",
            "Machine-learning sensitivity analyses",
            "Leave-one-validation-cohort sensitivity, random robust-gene panel baseline outputs, disease-control score stress test, matched random discovery-feature panel baseline, non-perfect-cohort summary, and cohort-adjusted score test.",
            [
                ("per_cohort_performance", PROJECT_DIR / "results/ml_sensitivity/elastic_net_external_per_cohort_performance.csv"),
                ("leave_one_cohort", PROJECT_DIR / "results/ml_sensitivity/leave_one_validation_cohort_sensitivity.csv"),
                ("random_panel_summary", PROJECT_DIR / "results/ml_sensitivity/random_robust_25_gene_panel_baseline_summary.csv"),
                ("random_panel_all", PROJECT_DIR / "results/ml_sensitivity/random_robust_25_gene_panel_baseline.csv"),
                ("random_panel_cohort_perf", PROJECT_DIR / "results/ml_sensitivity/random_robust_25_gene_panel_cohort_performance.csv"),
                ("gse110147_disease_control_scores", PROJECT_DIR / "results/ml_stress_tests/gse110147_excluded_ild_disease_control_scores.csv"),
                ("gse110147_disease_control_summary", PROJECT_DIR / "results/ml_stress_tests/gse110147_excluded_ild_disease_control_summary.csv"),
                ("matched_random_discovery_panel", PROJECT_DIR / "results/ml_stress_tests/matched_random_discovery_feature_panel_baseline.csv"),
                ("matched_random_discovery_summary", PROJECT_DIR / "results/ml_stress_tests/matched_random_discovery_feature_panel_summary.csv"),
                ("nonperfect_cohort_stress", PROJECT_DIR / "results/ml_stress_tests/nonperfect_cohort_stress_summary.csv"),
                ("cohort_adjusted_score_test", PROJECT_DIR / "results/ml_stress_tests/cohort_adjusted_external_logistic_association.csv"),
                ("auc_stress_qc", PROJECT_DIR / "results/ml_stress_tests/auc_stress_test_qc.csv"),
                ("figure_s13_manifest", PROJECT_DIR / "results/ml_stress_tests/figure_s13_manifest.csv"),
                ("sensitivity_qc", PROJECT_DIR / "results/ml_sensitivity/machine_learning_sensitivity_qc.csv"),
                ("sensitivity_manifest", PROJECT_DIR / "results/ml_sensitivity/machine_learning_sensitivity_manifest.csv"),
            ],
        )
    )
    files.append(
        write_workbook(
            "Additional_file_9_single_cell_localization.xlsx",
            "Single-cell localization summaries",
            "Single-cell target-expression summaries, donor-aware pseudobulk validation, broad-celltype mapping, localization tables, and validation QC.",
            [
                ("target_expression_summary", PROJECT_DIR / "results/single_cell_validation/single_cell_target_expression_summary_all.csv"),
                ("clean_delta_by_celltype", PROJECT_DIR / "results/single_cell_validation/single_cell_clean_ipf_control_delta_by_celltype.csv"),
                ("gene_top_celltype_localization", PROJECT_DIR / "results/single_cell_validation/single_cell_gene_top_celltype_localization.csv"),
                ("top_celltype_gene_pairs", PROJECT_DIR / "results/single_cell_validation/single_cell_clean_top_celltype_gene_changes.csv"),
                ("pseudobulk_donor_expression", PROJECT_DIR / "results/single_cell_pseudobulk/single_cell_pseudobulk_donor_celltype_expression.csv"),
                ("pseudobulk_differential", PROJECT_DIR / "results/single_cell_pseudobulk/single_cell_pseudobulk_differential_summary.csv"),
                ("pseudobulk_core_summary", PROJECT_DIR / "results/single_cell_pseudobulk/single_cell_pseudobulk_core_candidate_summary.csv"),
                ("pseudobulk_cell_counts", PROJECT_DIR / "results/single_cell_pseudobulk/single_cell_pseudobulk_broad_celltype_cell_count_summary.csv"),
                ("pseudobulk_method_notes", PROJECT_DIR / "results/single_cell_pseudobulk/single_cell_pseudobulk_method_notes.csv"),
                ("pseudobulk_dotplot_manifest", PROJECT_DIR / "results/single_cell_pseudobulk/single_cell_pseudobulk_donor_dotplot_manifest.csv"),
                ("broad_celltype_mapping", PROJECT_DIR / "results/single_cell_pseudobulk/single_cell_broad_celltype_mapping.csv"),
                ("broad_celltype_mapping_qc", PROJECT_DIR / "results/single_cell_pseudobulk/single_cell_broad_celltype_mapping_qc.csv"),
                ("pseudobulk_qc", PROJECT_DIR / "results/single_cell_pseudobulk/single_cell_pseudobulk_qc.csv"),
                ("manuscript_summary_qc", PROJECT_DIR / "results/single_cell_validation/single_cell_manuscript_summary_qc.csv"),
                ("single_cell_triple_qc", PROJECT_DIR / "results/single_cell_validation/single_cell_validation_triple_qc.csv"),
            ],
        )
    )
    files.append(
        write_workbook(
            "Additional_file_10_mechanistic_extension.xlsx",
            "Mechanistic extension outputs",
            "Marker scores, coexpression modules, curated ligand-receptor scoring, coexpression-neighborhood perturbation-priority proxy, and TNIK bridge tables.",
            [
                ("bulk_marker_scores", PROJECT_DIR / "results/mechanistic_extension/bulk_marker_scores.csv"),
                ("candidate_module_overlap", PROJECT_DIR / "results/mechanistic_extension/candidate_module_overlap.csv"),
                ("module_trait_correlations", PROJECT_DIR / "results/mechanistic_extension/coexpression_module_trait_correlations.csv"),
                ("curated_lr_delta", PROJECT_DIR / "results/mechanistic_extension/curated_ligand_receptor_interaction_delta.csv"),
                ("top_curated_lr", PROJECT_DIR / "results/mechanistic_extension/top_curated_ligand_receptor_interactions.csv"),
                ("perturbation_priority_proxy", PROJECT_DIR / "results/mechanistic_extension/perturbation_priority_proxy_summary.csv"),
                ("tnik_evidence", PROJECT_DIR / "results/mechanistic_extension/tnik_evidence_summary.csv"),
                ("mechanistic_qc", PROJECT_DIR / "results/mechanistic_extension/mechanistic_extension_qc.csv"),
            ],
        )
    )
    files.append(write_code_archive())
    files.append(
        write_binary_file(
            "Additional_file_12_pseudobulk_donor_plots.pdf",
            "Donor-level pseudobulk plots",
            "Supplementary donor-level pseudobulk dot/median plots for the core single-cell validation comparisons shown in Figure 5C.",
            PROJECT_DIR / "results/single_cell_pseudobulk/single_cell_pseudobulk_core_candidate_donor_dotplots.pdf",
        )
    )
    files.append(
        write_binary_file(
            "Additional_file_13_auc_stress_tests.pdf",
            "AUC disease-state stress-test plots",
            "Supplementary disease-control score distribution and matched random discovery-feature panel baseline for external ML boundary assessment.",
            PROJECT_DIR / "results/ml_stress_tests/additional_figure_s13_auc_stress_tests.pdf",
        )
    )
    files.append(
        write_binary_file(
            "Additional_file_14_mirna_program_stress_test.pdf",
            "miRNA target-program stress-test plots",
            "Supplementary miRTarBase target-set stress test and hsa-miR-375 target release-like score used to bound miRNA interpretation.",
            PROJECT_DIR / "results/mirna_program_support/additional_figure_s14_mirna_program_stress_test.pdf",
        )
    )

    manifest = pd.DataFrame(files)
    manifest.insert(0, "additional_file_number", range(1, len(manifest) + 1))
    manifest_path = OUT_DIR / "additional_files_manifest.csv"
    manifest.to_csv(manifest_path, index=False, encoding="utf-8-sig")
    (OUT_DIR / "additional_files_manifest.json").write_text(json.dumps(files, indent=2), encoding="utf-8")
    print(OUT_DIR)
    print(manifest.to_string(index=False))


if __name__ == "__main__":
    main()
